# Generated by Django 4.1.5 on 2023-02-15 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyer', '0004_alter_userprofile_mobile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='category',
            field=models.CharField(choices=[('ELECTRONICS', 'Electronics'), ('FASHION', 'Fashion'), ('HOME', 'Home'), ('SPORTS', 'Sports'), ('VEHICLES', 'Vehicles'), ('OTHER', 'Other')], max_length=20),
        ),
    ]
